create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  stripe_session_id text unique not null,
  payment_status text,
  customer_name text,
  email text,
  phone text,
  amount_sgd numeric(10,2),
  product_type text not null default 'pocket_wifi',
  plan_name text,
  country text,
  travel_start date,
  travel_end date,
  shipping_address jsonb,
  fulfilment_status text not null default 'awaiting_payment',
  courier_tracking text,
  return_tracking text,
  dispatched_at timestamptz,
  returned_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders add column if not exists product_type text not null default 'pocket_wifi';
alter table public.orders add column if not exists plan_name text;
alter table public.orders add column if not exists courier_tracking text;
alter table public.orders add column if not exists return_tracking text;
alter table public.orders add column if not exists dispatched_at timestamptz;
alter table public.orders add column if not exists returned_at timestamptz;
alter table public.orders add column if not exists notes text;
alter table public.orders enable row level security;

-- Stripe event idempotency ledger: Stripe may retry the same event multiple times.
-- processed_at stays null while side effects are in flight so an interrupted
-- delivery is retried instead of being mistaken for a completed event.
create table if not exists public.stripe_events (
  event_id text primary key,
  event_type text not null,
  received_at timestamptz not null default now(),
  processing_started_at timestamptz not null default now(),
  processed_at timestamptz
);
alter table public.stripe_events add column if not exists received_at timestamptz not null default now();
alter table public.stripe_events add column if not exists processing_started_at timestamptz not null default now();
alter table public.stripe_events alter column processed_at drop default;
alter table public.stripe_events alter column processed_at drop not null;
alter table public.stripe_events enable row level security;

-- Durable human-fulfilment notification ledger. One row per paid checkout.
-- The webhook records pending before SMTP and sent after SMTP succeeds. Failed
-- sends stay retryable without coupling the notification state to Stripe's
-- event-level idempotency record.
create table if not exists public.fulfilment_notifications (
  stripe_session_id text primary key,
  status text not null default 'pending' check (status in ('pending','sending','sent')),
  attempts integer not null default 0,
  last_attempt_at timestamptz,
  sent_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.fulfilment_notifications enable row level security;

-- No client policies: all operational tables are server/service-role only.
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_product_type_idx on public.orders(product_type);
create index if not exists orders_fulfilment_status_idx on public.orders(fulfilment_status);
create index if not exists orders_travel_start_idx on public.orders(travel_start);
create index if not exists stripe_events_processed_at_idx on public.stripe_events(processed_at desc);
create index if not exists fulfilment_notifications_status_idx on public.fulfilment_notifications(status, updated_at);
