create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  stripe_session_id text unique not null,
  payment_status text,
  customer_name text,
  email text,
  phone text,
  amount_sgd numeric(10,2),
  product_type text not null default 'pocket_wifi',
  plan_name text,
  country text,
  travel_start date,
  travel_end date,
  shipping_address jsonb,
  fulfilment_status text not null default 'awaiting_payment',
  courier_tracking text,
  return_tracking text,
  dispatched_at timestamptz,
  returned_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders add column if not exists product_type text not null default 'pocket_wifi';
alter table public.orders add column if not exists plan_name text;
alter table public.orders add column if not exists courier_tracking text;
alter table public.orders add column if not exists return_tracking text;
alter table public.orders add column if not exists dispatched_at timestamptz;
alter table public.orders add column if not exists returned_at timestamptz;
alter table public.orders add column if not exists notes text;
alter table public.orders enable row level security;

-- Stripe event idempotency ledger: Stripe may retry the same event multiple times.
-- processed_at stays null while side effects are in flight so an interrupted
-- delivery is retried instead of being mistaken for a completed event.
create table if not exists public.stripe_events (
  event_id text primary key,
  event_type text not null,
  received_at timestamptz not null default now(),
  processing_started_at timestamptz not null default now(),
  processed_at timestamptz
);
alter table public.stripe_events add column if not exists received_at timestamptz not null default now();
alter table public.stripe_events add column if not exists processing_started_at timestamptz not null default now();
alter table public.stripe_events alter column processed_at drop default;
alter table public.stripe_events alter column processed_at drop not null;
alter table public.stripe_events enable row level security;

-- Durable human-fulfilment notification ledger. One row per paid checkout.
-- The webhook records pending before SMTP and sent after SMTP succeeds. Failed
-- sends stay retryable without coupling the notification state to Stripe's
-- event-level idempotency record.
create table if not exists public.fulfilment_notifications (
  stripe_session_id text primary key,
  status text not null default 'pending' check (status in ('pending','sending','sent')),
  attempts integer not null default 0,
  last_attempt_at timestamptz,
  sent_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.fulfilment_notifications enable row level security;

-- Durable Meta CAPI delivery ledger. Stripe retries remain safe when Meta is
-- temporarily unavailable, and a successfully delivered Purchase is never sent
-- again by a later webhook event for the same Checkout Session.
create table if not exists public.meta_purchase_deliveries (
  stripe_session_id text primary key,
  status text not null default 'pending' check (status in ('pending','sending','sent')),
  -- Keep the original signed Stripe event timestamp. Retried CAPI deliveries
  -- must use the same Purchase event identity and time for reliable dedupe.
  event_time bigint check (event_time is null or event_time > 0),
  attempts integer not null default 0,
  last_attempt_at timestamptz,
  sent_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.meta_purchase_deliveries add column if not exists event_time bigint check (event_time is null or event_time > 0);
alter table public.meta_purchase_deliveries enable row level security;

-- Short-lived inventory reservations close the gap between an availability
-- check and Stripe Checkout Session creation. The reservation RPC serializes
-- competing checkouts, so two customers cannot both claim the final router.
create table if not exists public.checkout_reservations (
  checkout_request_id text primary key,
  stripe_session_id text unique,
  travel_start date not null,
  travel_end date not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  check (travel_end >= travel_start)
);
alter table public.checkout_reservations enable row level security;

create or replace function public.qy_reserve_pocket_wifi(
  p_checkout_request_id text,
  p_travel_start date,
  p_travel_end date,
  p_inventory integer,
  p_expires_at timestamptz,
  p_stripe_hold_count integer default 0,
  p_stripe_hold_request_ids text[] default array[]::text[]
)
returns table(reserved boolean, remaining integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_existing public.checkout_reservations%rowtype;
  v_booked integer;
  v_reserved integer;
  v_committed integer;
begin
  if p_checkout_request_id is null or p_checkout_request_id !~ '^[A-Za-z0-9_-]{16,80}$' then
    raise exception 'invalid checkout request id';
  end if;
  if p_travel_start is null or p_travel_end is null or p_travel_end < p_travel_start then
    raise exception 'invalid reservation dates';
  end if;

  -- A single transaction-level lock makes capacity calculation plus insertion
  -- atomic across every application instance.
  perform pg_advisory_xact_lock(hashtext('qy_roam_pocket_wifi_checkout'));
  delete from public.checkout_reservations where expires_at <= now();

  select * into v_existing
  from public.checkout_reservations
  where checkout_request_id = p_checkout_request_id;
  if found then
    if v_existing.travel_start <> p_travel_start or v_existing.travel_end <> p_travel_end then
      raise exception 'checkout request id was already used for different dates';
    end if;
    return query select true, greatest(0, p_inventory - 1);
    return;
  end if;

  select count(*)::integer into v_booked
  from public.orders
  where product_type = 'pocket_wifi'
    and payment_status = 'paid'
    and travel_start <= p_travel_end
    and travel_end >= p_travel_start
    -- A legacy order may have been marked cancelled after dispatch. It is
    -- still physically committed until the return is recorded, so it must not
    -- make a router available to an overlapping booking. Conversely, a
    -- recorded return is physical proof that the router is available again;
    -- do not wait for a separate administrative close to release capacity.
    and (
      fulfilment_status not in ('cancelled', 'payment_failed', 'returned', 'closed')
      or (fulfilment_status = 'cancelled' and dispatched_at is not null and returned_at is null)
    );

  -- Stripe holds passed by the app are counted once. Reservations already
  -- represented by those sessions are excluded from the database count.
  select count(*)::integer into v_reserved
  from public.checkout_reservations
  where expires_at > now()
    and travel_start <= p_travel_end
    and travel_end >= p_travel_start
    and not (checkout_request_id = any(coalesce(p_stripe_hold_request_ids, array[]::text[])));

  v_committed := v_booked + v_reserved + greatest(0, coalesce(p_stripe_hold_count, 0));
  if p_inventory < 1 or v_committed >= p_inventory then
    return query select false, greatest(0, p_inventory - v_committed);
    return;
  end if;

  insert into public.checkout_reservations (
    checkout_request_id, travel_start, travel_end, expires_at
  ) values (
    p_checkout_request_id, p_travel_start, p_travel_end, p_expires_at
  );
  return query select true, greatest(0, p_inventory - v_committed - 1);
end;
$$;

revoke all on function public.qy_reserve_pocket_wifi(text,date,date,integer,timestamptz,integer,text[]) from public;
grant execute on function public.qy_reserve_pocket_wifi(text,date,date,integer,timestamptz,integer,text[]) to service_role;

-- Manual paid Pocket WiFi orders must share checkout's inventory boundary.
-- Checking capacity in the admin API and then inserting separately would let
-- two operators sell the final router at the same time. This function keeps
-- the capacity calculation and durable order creation under the same advisory
-- lock used for Checkout reservations.
create or replace function public.qy_create_manual_pocket_wifi_order(
  p_stripe_session_id text,
  p_customer_name text,
  p_email text,
  p_phone text,
  p_amount_sgd numeric,
  p_plan_name text,
  p_country text,
  p_travel_start date,
  p_travel_end date,
  p_notes text,
  p_inventory integer
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_booked integer;
  v_reserved integer;
  v_order public.orders%rowtype;
begin
  if coalesce(length(trim(p_stripe_session_id)), 0) = 0 then raise exception 'manual order reference is required'; end if;
  if p_amount_sgd is null or p_amount_sgd <= 0 then raise exception 'manual order amount must be positive'; end if;
  if coalesce(length(trim(p_country)), 0) = 0 then raise exception 'Pocket WiFi destination is required'; end if;
  if p_travel_start is null or p_travel_end is null or p_travel_end < p_travel_start then raise exception 'invalid Pocket WiFi travel dates'; end if;

  perform pg_advisory_xact_lock(hashtext('qy_roam_pocket_wifi_checkout'));
  delete from public.checkout_reservations where expires_at <= now();

  select count(*)::integer into v_booked
  from public.orders
  where product_type = 'pocket_wifi'
    and payment_status = 'paid'
    and travel_start <= p_travel_end
    and travel_end >= p_travel_start
    and (
      fulfilment_status not in ('cancelled', 'payment_failed', 'returned', 'closed')
      or (fulfilment_status = 'cancelled' and dispatched_at is not null and returned_at is null)
    );

  select count(*)::integer into v_reserved
  from public.checkout_reservations
  where expires_at > now()
    and travel_start <= p_travel_end
    and travel_end >= p_travel_start;

  if p_inventory < 1 or v_booked + v_reserved >= p_inventory then
    raise exception 'Pocket WiFi is sold out or reserved for these travel dates';
  end if;

  insert into public.orders (
    stripe_session_id, payment_status, customer_name, email, phone, amount_sgd,
    product_type, plan_name, country, travel_start, travel_end, fulfilment_status,
    notes, updated_at
  ) values (
    p_stripe_session_id, 'paid', p_customer_name, p_email, p_phone, p_amount_sgd,
    'pocket_wifi', p_plan_name, p_country, p_travel_start, p_travel_end, 'paid',
    p_notes, now()
  ) returning * into v_order;
  return v_order;
end;
$$;
revoke all on function public.qy_create_manual_pocket_wifi_order(text,text,text,text,numeric,text,text,date,date,text,integer) from public;
grant execute on function public.qy_create_manual_pocket_wifi_order(text,text,text,text,numeric,text,text,date,date,text,integer) to service_role;

-- No client policies: all operational tables are server/service-role only.
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_product_type_idx on public.orders(product_type);
create index if not exists orders_fulfilment_status_idx on public.orders(fulfilment_status);
create index if not exists orders_travel_start_idx on public.orders(travel_start);
create index if not exists stripe_events_processed_at_idx on public.stripe_events(processed_at desc);
create index if not exists fulfilment_notifications_status_idx on public.fulfilment_notifications(status, updated_at);
create index if not exists meta_purchase_deliveries_status_idx on public.meta_purchase_deliveries(status, updated_at);
create index if not exists checkout_reservations_dates_idx on public.checkout_reservations(travel_start, travel_end, expires_at);

-- Operations tables backing the protected admin area. Keep these in the same
-- deployable schema as checkout: an otherwise healthy order database must not
-- leave the fulfilment, inventory, reporting or CRM screens querying tables
-- that were never created on a new production project.
create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  name text not null,
  product_type text not null default 'pocket_wifi',
  serial_no text,
  status text not null default 'available',
  quantity_on_hand integer not null default 0 check (quantity_on_hand >= 0),
  reorder_level integer not null default 0 check (reorder_level >= 0),
  unit_cost_sgd numeric(10,2) not null default 0 check (unit_cost_sgd >= 0),
  location text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (product_type in ('pocket_wifi', 'esim'))
);
alter table public.inventory_items enable row level security;

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint not null references public.inventory_items(id) on delete restrict,
  movement_type text not null,
  quantity integer not null check (quantity <> 0),
  reference text,
  notes text,
  created_at timestamptz not null default now()
);
alter table public.inventory_movements enable row level security;

-- A dispatched rental is tied to the stock record that supplied it. Keeping
-- this on the order lets the return restore the exact same pool of devices,
-- rather than relying on an operator to remember which SKU was sent.
alter table public.orders add column if not exists inventory_item_id bigint references public.inventory_items(id) on delete restrict;
create index if not exists orders_inventory_item_idx on public.orders(inventory_item_id);

-- Inventory quantity and its audit record must change atomically. The admin
-- API uses only this function for adjustments, dispatches and returns.
create or replace function public.qy_adjust_inventory(
  p_item_id bigint,
  p_delta integer,
  p_type text,
  p_reference text default null,
  p_notes text default null
)
returns public.inventory_items
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item public.inventory_items%rowtype;
begin
  if p_item_id is null or p_item_id < 1 then raise exception 'invalid inventory item'; end if;
  if p_delta is null or p_delta = 0 then raise exception 'inventory adjustment must not be zero'; end if;
  if coalesce(length(trim(p_type)), 0) = 0 then raise exception 'movement type is required'; end if;

  update public.inventory_items
  set quantity_on_hand = quantity_on_hand + p_delta,
      updated_at = now()
  where id = p_item_id
    and quantity_on_hand + p_delta >= 0
  returning * into v_item;
  if not found then
    if exists (select 1 from public.inventory_items where id = p_item_id) then
      raise exception 'inventory quantity cannot be negative';
    end if;
    raise exception 'inventory item not found';
  end if;

  insert into public.inventory_movements (inventory_item_id, movement_type, quantity, reference, notes)
  values (p_item_id, left(trim(p_type), 40), p_delta, nullif(left(trim(coalesce(p_reference, '')), 120), ''), nullif(left(trim(coalesce(p_notes, '')), 1000), ''));
  return v_item;
end;
$$;
revoke all on function public.qy_adjust_inventory(bigint,integer,text,text,text) from public;
grant execute on function public.qy_adjust_inventory(bigint,integer,text,text,text) to service_role;

-- The physical hand-off and receipt boundaries must update an order and its
-- stock ledger in one transaction. A browser-side sequence of "set status",
-- then "adjust stock" can otherwise leave a dispatched router available (or a
-- returned router missing) if either request is interrupted.
create or replace function public.qy_transition_pocket_wifi_order(
  p_order_id bigint,
  p_expected_status text,
  p_next_status text,
  p_courier_tracking text default null,
  p_return_tracking text default null,
  p_notes text default null,
  p_inventory_item_id bigint default null
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_item public.inventory_items%rowtype;
  v_now timestamptz := now();
  v_item_id bigint;
begin
  select * into v_order from public.orders where id = p_order_id for update;
  if not found then raise exception 'order not found'; end if;
  if v_order.product_type <> 'pocket_wifi' or v_order.payment_status <> 'paid' then
    raise exception 'only paid Pocket WiFi orders can be transitioned here';
  end if;
  if v_order.fulfilment_status <> p_expected_status then
    raise exception 'order changed since it was loaded';
  end if;

  if not (
    p_next_status = p_expected_status or
    (p_expected_status = 'paid' and p_next_status in ('packing', 'dispatched', 'cancelled')) or
    (p_expected_status = 'packing' and p_next_status in ('paid', 'dispatched', 'cancelled')) or
    (p_expected_status = 'dispatched' and p_next_status in ('packing', 'with_customer', 'return_due', 'returned')) or
    (p_expected_status = 'with_customer' and p_next_status in ('dispatched', 'return_due', 'returned')) or
    (p_expected_status = 'return_due' and p_next_status in ('with_customer', 'returned')) or
    (p_expected_status = 'returned' and p_next_status = 'closed')
  ) then raise exception 'invalid Pocket WiFi fulfilment transition'; end if;

  if p_next_status = 'dispatched' and v_order.dispatched_at is null then
    if nullif(trim(coalesce(p_courier_tracking, '')), '') is null then raise exception 'courier tracking is required before dispatch'; end if;
    v_item_id := coalesce(p_inventory_item_id, v_order.inventory_item_id);
    if v_item_id is null then raise exception 'a Pocket WiFi inventory item is required before dispatch'; end if;
    -- Quantity alone is not sufficient evidence that a router may leave the
    -- warehouse. An operator can deliberately quarantine a stock record for
    -- damage, cleaning or maintenance while it still has a positive balance.
    -- Enforce its operational availability inside this transaction, rather
    -- than trusting the admin UI's filtered device list.
    select * into v_item from public.inventory_items
    where id = v_item_id
      and product_type = 'pocket_wifi'
      and status = 'available'
    for update;
    if not found then
      if exists (select 1 from public.inventory_items where id = v_item_id and product_type = 'pocket_wifi') then
        raise exception 'selected Pocket WiFi inventory item is not available for dispatch';
      end if;
      raise exception 'Pocket WiFi inventory item not found';
    end if;
    if v_item.quantity_on_hand < 1 then raise exception 'selected Pocket WiFi inventory item is out of stock'; end if;
    update public.inventory_items set quantity_on_hand = quantity_on_hand - 1, updated_at = v_now where id = v_item_id;
    insert into public.inventory_movements (inventory_item_id, movement_type, quantity, reference, notes)
    values (v_item_id, 'dispatch', -1, left(v_order.stripe_session_id, 120), nullif(left(trim(coalesce(p_courier_tracking, '')), 1000), ''));
  elsif p_next_status = 'returned' and v_order.returned_at is null then
    if nullif(trim(coalesce(p_return_tracking, '')), '') is null then raise exception 'return tracking is required before receipt'; end if;
    v_item_id := v_order.inventory_item_id;
    if v_item_id is null then raise exception 'dispatched Pocket WiFi order has no inventory item to return'; end if;
    select * into v_item from public.inventory_items where id = v_item_id and product_type = 'pocket_wifi' for update;
    if not found then raise exception 'assigned Pocket WiFi inventory item not found'; end if;
    update public.inventory_items set quantity_on_hand = quantity_on_hand + 1, updated_at = v_now where id = v_item_id;
    insert into public.inventory_movements (inventory_item_id, movement_type, quantity, reference, notes)
    values (v_item_id, 'return', 1, left(v_order.stripe_session_id, 120), nullif(left(trim(coalesce(p_return_tracking, '')), 1000), ''));
  end if;

  update public.orders set
    fulfilment_status = p_next_status,
    courier_tracking = case when p_courier_tracking is null then courier_tracking else nullif(left(trim(p_courier_tracking), 200), '') end,
    return_tracking = case when p_return_tracking is null then return_tracking else nullif(left(trim(p_return_tracking), 200), '') end,
    notes = case when p_notes is null then notes else left(p_notes, 1000) end,
    inventory_item_id = coalesce(v_order.inventory_item_id, case when p_next_status = 'dispatched' then p_inventory_item_id end),
    dispatched_at = case when p_next_status = 'dispatched' and dispatched_at is null then v_now else dispatched_at end,
    returned_at = case when p_next_status = 'returned' and returned_at is null then v_now else returned_at end,
    updated_at = v_now
  where id = p_order_id
  returning * into v_order;
  return v_order;
end;
$$;
revoke all on function public.qy_transition_pocket_wifi_order(bigint,text,text,text,text,text,bigint) from public;
grant execute on function public.qy_transition_pocket_wifi_order(bigint,text,text,text,text,text,bigint) to service_role;

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  email text,
  phone text,
  name text,
  status text not null default 'lead',
  source text,
  notes text,
  total_orders integer not null default 0 check (total_orders >= 0),
  lifetime_value_sgd numeric(10,2) not null default 0 check (lifetime_value_sgd >= 0),
  last_order_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (email is not null or phone is not null)
);
alter table public.customers enable row level security;

create table if not exists public.crm_activities (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id) on delete set null,
  activity_type text not null default 'note',
  subject text,
  detail text,
  due_at timestamptz,
  completed_at timestamptz,
  owner text,
  created_at timestamptz not null default now()
);
alter table public.crm_activities enable row level security;

create table if not exists public.sales_opportunities (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id) on delete set null,
  title text not null,
  product_type text,
  stage text not null default 'lead',
  probability numeric(5,2) not null default 0 check (probability between 0 and 100),
  expected_value_sgd numeric(10,2) not null default 0 check (expected_value_sgd >= 0),
  expected_close_date date,
  source text,
  owner text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.sales_opportunities enable row level security;

create table if not exists public.forecasts (
  id bigint generated by default as identity primary key,
  forecast_month date not null,
  product_type text not null,
  forecast_orders integer not null default 0 check (forecast_orders >= 0),
  forecast_revenue_sgd numeric(10,2) not null default 0 check (forecast_revenue_sgd >= 0),
  forecast_units integer not null default 0 check (forecast_units >= 0),
  method text not null default 'management',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (forecast_month, product_type)
);
alter table public.forecasts enable row level security;

create table if not exists public.closing_periods (
  id bigint generated by default as identity primary key,
  period_start date not null,
  period_end date not null,
  status text not null default 'open' check (status in ('open', 'closed')),
  gross_sales_sgd numeric(10,2) not null default 0,
  refunds_sgd numeric(10,2) not null default 0,
  net_sales_sgd numeric(10,2) not null default 0,
  fees_sgd numeric(10,2) not null default 0,
  cogs_sgd numeric(10,2) not null default 0,
  gross_profit_sgd numeric(10,2) not null default 0,
  closed_by text,
  closed_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (period_end >= period_start)
);
alter table public.closing_periods enable row level security;

-- Reporting is derived directly from the authoritative orders ledger, so it
-- cannot drift from webhook-persisted paid revenue.
create or replace view public.sales_daily_summary with (security_invoker = true) as
select
  (created_at at time zone 'Asia/Singapore')::date as sales_date,
  product_type,
  count(*)::integer as paid_orders,
  coalesce(sum(amount_sgd), 0)::numeric(12,2) as revenue_sgd,
  coalesce(avg(amount_sgd), 0)::numeric(12,2) as avg_order_value_sgd
from public.orders
where payment_status = 'paid'
group by 1, 2;

create index if not exists inventory_items_product_type_idx on public.inventory_items(product_type);
create index if not exists inventory_movements_item_created_idx on public.inventory_movements(inventory_item_id, created_at desc);
create index if not exists customers_last_order_idx on public.customers(last_order_at desc);
create index if not exists crm_activities_due_idx on public.crm_activities(due_at) where completed_at is null;
create index if not exists sales_opportunities_updated_idx on public.sales_opportunities(updated_at desc);
create index if not exists forecasts_month_product_idx on public.forecasts(forecast_month, product_type);
create index if not exists closing_periods_end_idx on public.closing_periods(period_end desc);
