import { getSupabaseAdmin } from '@/lib/supabaseAdmin';
export const dynamic='force-dynamic';
const card={border:'1px solid #e4e8ef',borderRadius:16,padding:18,background:'#fff'} as const;
const money=(v:any)=>`S$${Number(v||0).toFixed(2)}`;
export default async function CrmPage(){
 const db=getSupabaseAdmin();
 const customers=db?((await db.from('customers').select('*').order('last_order_at',{ascending:false}).limit(500)).data??[]):[];
 const opps=db?((await db.from('sales_opportunities').select('*').order('updated_at',{ascending:false}).limit(200)).data??[]):[];
 const pipeline=opps.filter((x:any)=>!['won','lost'].includes(x.stage)).reduce((s:any,x:any)=>s+Number(x.expected_value_sgd||0)*Number(x.probability||0)/100,0);
 return <main className="wrap section legal" style={{maxWidth:1280}}><span className="eyebrow">CRM</span><h1>Customers & sales pipeline</h1>{!db&&<div style={card}><strong>Database connection required.</strong></div>}{db&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}><div style={card}><small>Customers</small><h2>{customers.length}</h2></div><div style={card}><small>Open opportunities</small><h2>{opps.filter((x:any)=>!['won','lost'].includes(x.stage)).length}</h2></div><div style={card}><small>Weighted pipeline</small><h2>{money(pipeline)}</h2></div></div><h2 style={{marginTop:28}}>Customers</h2>{customers.length===0?<p>No CRM customers yet.</p>:<div style={{overflowX:'auto',...card}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:760}}><thead><tr><th align="left">Customer</th><th align="left">Status</th><th align="right">Orders</th><th align="right">LTV</th><th align="left">Last order</th></tr></thead><tbody>{customers.map((c:any)=><tr key={c.id} style={{borderTop:'1px solid #e5e7eb'}}><td><strong>{c.name||'-'}</strong><br/><small>{c.email||c.phone||'-'}</small></td><td>{c.status}</td><td align="right">{c.total_orders}</td><td align="right">{money(c.lifetime_value_sgd)}</td><td>{c.last_order_at?new Date(c.last_order_at).toLocaleDateString('en-SG'):'-'}</td></tr>)}</tbody></table></div>}<h2 style={{marginTop:28}}>Sales pipeline</h2>{opps.length===0?<p>No opportunities yet.</p>:<div style={{overflowX:'auto',...card}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:760}}><thead><tr><th align="left">Opportunity</th><th align="left">Stage</th><th align="left">Product</th><th align="right">Value</th><th align="right">Probability</th><th align="left">Expected close</th></tr></thead><tbody>{opps.map((o:any)=><tr key={o.id} style={{borderTop:'1px solid #e5e7eb'}}><td>{o.title}</td><td>{o.stage}</td><td>{o.product_type||'-'}</td><td align="right">{money(o.expected_value_sgd)}</td><td align="right">{o.probability}%</td><td>{o.expected_close_date||'-'}</td></tr>)}</tbody></table></div>}</>}</main>;
}
