'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

const box={border:'1px solid #e4e8ef',borderRadius:16,padding:18,background:'#fff',margin:'18px 0'} as const;
const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10} as const;
const input={width:'100%',padding:'10px 12px',border:'1px solid #d8dee8',borderRadius:9,boxSizing:'border-box' as const};

function FormBox({title,children}:{title:string,children:any}){return <section style={box}><h3 style={{marginTop:0}}>{title}</h3>{children}</section>}
function useSubmit(){const router=useRouter();const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');async function submit(payload:any){setBusy(true);setMsg('');try{const r=await fetch('/api/admin/ops',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Operation failed');setMsg('Saved');router.refresh();return true}catch(e:any){setMsg(e.message||'Operation failed');return false}finally{setBusy(false)}}return{busy,msg,submit}}
function Msg({busy,msg}:{busy:boolean,msg:string}){return <small style={{marginLeft:10}}>{busy?'Saving…':msg}</small>}

export function InventoryCreateForm(){const s=useSubmit();async function go(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await s.submit({action:'inventory_create',...Object.fromEntries(f)}))e.currentTarget.reset()}return <FormBox title="Add inventory item"><form onSubmit={go}><div style={grid}><input style={input} name="sku" placeholder="SKU" required/><input style={input} name="name" placeholder="Item name" required/><select style={input} name="product_type"><option value="pocket_wifi">Pocket WiFi</option><option value="esim">eSIM / digital stock</option></select><input style={input} name="serial_no" placeholder="Serial no. (optional)"/><input style={input} name="quantity_on_hand" type="number" min="0" defaultValue="0" placeholder="Qty"/><input style={input} name="reorder_level" type="number" min="0" defaultValue="2"/><input style={input} name="unit_cost_sgd" type="number" min="0" step="0.01" placeholder="Unit cost S$"/><input style={input} name="location" placeholder="Location"/></div><div style={{marginTop:12}}><button className="primary">Add item</button><Msg {...s}/></div></form></FormBox>}
export function InventoryAdjustForm({items}:{items:any[]}){const s=useSubmit();async function go(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await s.submit({action:'inventory_adjust',...Object.fromEntries(f)})}return <FormBox title="Stock movement / adjustment"><form onSubmit={go}><div style={grid}><select style={input} name="item_id" required>{items.map(x=><option key={x.id} value={x.id}>{x.sku} · {x.name} ({x.quantity_on_hand})</option>)}</select><input style={input} name="delta" type="number" placeholder="Qty change, e.g. -1 / +5" required/><select style={input} name="movement_type"><option>adjustment</option><option>dispatch</option><option>return</option><option>purchase</option><option>write_off</option></select><input style={input} name="reference" placeholder="Order / PO reference"/><input style={input} name="notes" placeholder="Notes"/></div><div style={{marginTop:12}}><button className="primary">Post movement</button><Msg {...s}/></div></form></FormBox>}

export function CustomerCreateForm(){const s=useSubmit();async function go(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await s.submit({action:'customer_create',...Object.fromEntries(f)}))e.currentTarget.reset()}return <FormBox title="Add CRM customer / lead"><form onSubmit={go}><div style={grid}><input style={input} name="name" placeholder="Name"/><input style={input} name="email" type="email" placeholder="Email"/><input style={input} name="phone" placeholder="Phone"/><select style={input} name="status"><option>lead</option><option>active</option><option>inactive</option></select><input style={input} name="source" placeholder="Source"/><input style={input} name="notes" placeholder="Notes"/></div><div style={{marginTop:12}}><button className="primary">Add customer</button><Msg {...s}/></div></form></FormBox>}
export function ActivityForm({customers}:{customers:any[]}){const s=useSubmit();async function go(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await s.submit({action:'activity_create',...Object.fromEntries(f)}))e.currentTarget.reset()}return <FormBox title="Add CRM note / follow-up"><form onSubmit={go}><div style={grid}><select style={input} name="customer_id"><option value="">General activity</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name||c.email||c.phone}</option>)}</select><select style={input} name="activity_type"><option>note</option><option>call</option><option>whatsapp</option><option>email</option><option>task</option></select><input style={input} name="subject" placeholder="Subject"/><input style={input} name="detail" placeholder="Detail"/><input style={input} name="due_at" type="datetime-local"/><input style={input} name="owner" placeholder="Owner"/></div><div style={{marginTop:12}}><button className="primary">Save activity</button><Msg {...s}/></div></form></FormBox>}
export function OpportunityForm({customers}:{customers:any[]}){const s=useSubmit();async function go(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await s.submit({action:'opportunity_create',...Object.fromEntries(f)}))e.currentTarget.reset()}return <FormBox title="Create sales opportunity"><form onSubmit={go}><div style={grid}><input style={input} name="title" placeholder="Opportunity" required/><select style={input} name="customer_id"><option value="">No linked customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name||c.email||c.phone}</option>)}</select><select style={input} name="product_type"><option value="pocket_wifi">Pocket WiFi</option><option value="esim">eSIM</option><option value="">Mixed / other</option></select><select style={input} name="stage"><option>lead</option><option>qualified</option><option>proposal</option><option>negotiation</option><option>won</option><option>lost</option></select><input style={input} name="probability" type="number" min="0" max="100" defaultValue="20"/><input style={input} name="expected_value_sgd" type="number" min="0" step="0.01" placeholder="Expected S$"/><input style={input} name="expected_close_date" type="date"/><input style={input} name="owner" placeholder="Owner"/></div><div style={{marginTop:12}}><button className="primary">Create opportunity</button><Msg {...s}/></div></form></FormBox>}
export function OpportunityStage({id,stage,probability}:{id:number,stage:string,probability:number}){const s=useSubmit();async function go(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await s.submit({action:'opportunity_stage',id,...Object.fromEntries(f)})}return <form onSubmit={go} style={{display:'flex',gap:6,alignItems:'center'}}><select name="stage" defaultValue={stage} style={{...input,width:120}}><option>lead</option><option>qualified</option><option>proposal</option><option>negotiation</option><option>won</option><option>lost</option></select><input name="probability" type="number" min="0" max="100" defaultValue={probability} style={{...input,width:72}}/><button>Save</button></form>}

export function ForecastForm(){const s=useSubmit();async function go(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await s.submit({action:'forecast_upsert',...Object.fromEntries(f)})}return <FormBox title="Add / replace monthly forecast"><form onSubmit={go}><div style={grid}><input style={input} name="forecast_month" type="date" required/><select style={input} name="product_type"><option value="pocket_wifi">Pocket WiFi</option><option value="esim">eSIM</option></select><input style={input} name="forecast_orders" type="number" min="0" placeholder="Orders"/><input style={input} name="forecast_revenue_sgd" type="number" min="0" step="0.01" placeholder="Revenue S$"/><input style={input} name="forecast_units" type="number" min="0" placeholder="Units"/><select style={input} name="method"><option>management</option><option>run_rate</option><option>seasonal</option></select><input style={input} name="notes" placeholder="Assumptions"/></div><div style={{marginTop:12}}><button className="primary">Save forecast</button><Msg {...s}/></div></form></FormBox>}

export function ClosingForm(){const s=useSubmit();async function go(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await s.submit({action:'close_period',...Object.fromEntries(f),lock:f.get('lock')==='on'})}return <FormBox title="Prepare / close accounting period"><form onSubmit={go}><div style={grid}><input style={input} name="period_start" type="date" required/><input style={input} name="period_end" type="date" required/><input style={input} name="refunds_sgd" type="number" min="0" step="0.01" defaultValue="0" placeholder="Refunds"/><input style={input} name="fees_sgd" type="number" min="0" step="0.01" defaultValue="0" placeholder="Payment fees"/><input style={input} name="cogs_sgd" type="number" min="0" step="0.01" defaultValue="0" placeholder="COGS"/><input style={input} name="closed_by" placeholder="Closed by" defaultValue="qyadmin"/><input style={input} name="notes" placeholder="Reconciliation notes"/></div><label style={{display:'block',marginTop:12}}><input type="checkbox" name="lock"/> Lock period as closed</label><div style={{marginTop:12}}><button className="primary">Calculate & save period</button><Msg {...s}/></div></form></FormBox>}
